version: "3"

services: 
    web:
      container_name: backend
      restart: always
      build: .
      ports: 
        - "5000:3000"
      links:
        - mongo
      volumes:
          - .:/app
    mongo:
      container_name: mongodb
      image: mongo
      ports: 
        - "27017:27017"
      logging: 
        driver: none
